# Generated by Django 4.2.2 on 2023-06-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0002_image_alter_auto_status_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='status',
            field=models.CharField(choices=[('free', 'FREE'), ('booked', 'BOOKED'), ('taken', 'TAKEN')], default='free', max_length=7),
        ),
    ]
