# Generated by Django 4.2.2 on 2023-06-25 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0003_alter_auto_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name_plural': 'Авто'},
        ),
    ]
