# Generated by Django 4.2.1 on 2023-06-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pesron',
        ),
    ]
