# Generated by Django 4.2.1 on 2023-06-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_articles', '0002_delete_pesron'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='article',
        ),
    ]
