# Generated by Django 4.2.1 on 2023-06-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appreg_article', '0003_remove_article_author_article_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_id',
            new_name='author',
        ),
    ]
