# Generated by Django 4.2.2 on 2023-06-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsharing', '0002_alter_auto_vin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='vin_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
